version: "3.7"

services:
  vouch:
    hostname: vouch
    image: sharp6292/vouch
    environment:
      OAUTH_PROVIDER: google
      OAUTH_CALLBACK_URLS: ${CALLBACK_URL:?err}
      VOUCH_WHITELIST: ${ADMIN_EMAIL:?err}
      OAUTH_CLIENT_ID: ${VOUCHID:?err}
      OAUTH_CLIENT_SECRET: ${VOUCHSECRET:?err}
      VOUCH_DOMAINS: ${DOMAIN:?err}

    restart: always

networks:
    default:
        external:
            name: sharpnet
