version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: "Build"
          command: |
            start=`date +%s`

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull sharp6292/vouch:latest || true
            docker build --cache-from sharp6292/vouch:latest -t sharp6292/vouch:latest .
            docker push sharp6292/vouch:latest

            end=`date +%s`

            runtime=$((end-start))
            sleep (300-runtime)

  deploy:
    docker:
      - image: cimg/base:2020.01

    steps:
      - checkout

      - run:
          name: "Install SharpCD"
          command: |
            wget https://github.com/Sharpz7/sharpcd/releases/download/0.1.0/linux.tar.gz
            sudo tar -C /usr/local/bin/ -zxvf linux.tar.gz
            rm -r linux.tar.gz

            chmod u+x /usr/local/bin/sharpcd

      - run:
          name: "Setup Env"
          command: |
            echo "VOUCHID=${VOUCHID}" >> .env
            echo "VOUCHSECRET=${VOUCHSECRET}" >> .env
            echo "DOMAIN=${DOMAIN}" >> .env
            echo "ADMIN_EMAIL=${ADMIN_EMAIL}" >> .env
            echo "CALLBACK_URL=${CALLBACK_URL}" >> .env

      - run:
          name: "SharpCD Deploy"
          command: |
            sharpcd --secret ${SHARPCD_SECRET}

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: General


      - deploy:
          context: General
          requires:
            - build

          filters:
            branches:
              only: main